Feature/eslint and prettier
the38th/TaskManager pull request #18
Opened 2021-05-28 10:47 UTC by the38th

опять возникло несколько вопросов в процессе выполнения

1. в документации к webpacker-react написано "Webpacker-React contains two parts: a Javascript module and a Ruby gem. Both of those components respect semantic versioning. When upgrading the gem, you need to upgrade the NPM module to the same minor version. New patch versions can be released for each of the two independently, so it is ok to have the NPM module at version A.X.Y and the gem at version A.X.Z, but you should never have a different A or X." а у меня гем версии 1.0.0, а модуль версии 0.3.2, хотя всё сделано по инструкции. Если надо обновить модуль до версии 1.0.0, то как это сделать? в доках я ничего про это не нашёл
2. В задании написано "Попробовать написать в начале файла TaskBoard.js вызов дебаггера debugger;. Настроить конфиг так, чтобы это действие вызывало не error, а warning.", но в .eslintrc уже написано "no-debugger": 1. В задании точно всё правильно?
3. В инструкции к установке eslint написано что ему требуется чтобы был установлен Node.js, я потом посмотрел в докер файле она уже ставится, а вот npm не ставится, и я так понимаю что его и нет, как минимум потому что "npm --vesrion" в контейнере не работает. Откуда тогда package.json взялся, его yarn создал?
3.1 А если нам понадобится ставить пакеты через npm нужно будет установить его в контейнере или можно будет ставить из системы и оно через тома докера подцепиться? Или yarn может всё то же самое что и npm и пользоваться npm нам в обучении не придётся?
4. Это ничего что я тут вопросы задаю, а не в чате(в чате мне немного стеснительно)?

2021-05-31 19:08 UTC, greybutton requested changes
1 пока лучше гем 0.3.2, с бетой гема могут быть проблемы
2 это ок
3 да, ярн создал package.json
3.1 ставить нужно с помощью yarn в докере, yarn по сути тоже самое что npm. И yarn идет с рельсами. На лекции рассказывал различия между ними, если пропустил, можешь погуглить `yarn npm difference`
4 да, ок

2021-05-31 19:08 UTC, greybutton commented on .vscode/settings.json
> +   }
это твои локальные настройки, они не должны быть в проекте

2021-05-31 19:08 UTC, greybutton commented on Gemfile
> +gem 'webpacker-react', "~> 1.0.0.beta.1"
лучше поставить последнюю стабильную версию 0.3.2

2021-06-01 08:01 UTC, the38th commented
понял, спасибо

2021-06-02 16:35 UTC, greybutton approved these changes

2021-06-03 12:54 UTC, merged