Feature/assignee
the38th/TaskManager pull request #22
Opened 2021-06-06 14:48 UTC by the38th

Я подумал, что импортируя TaskPresenter, каждый раз должен создаваться новый экземпляр PropTypesPresenter, так как в самом TaskPresenter'e написано "export default new PropTypesPresenter". Но я вписал в конструктор PropTypesPresenter'a вывод в консоль, и он сработал только один раз. т.е. я так понял что всё таки создаётся только один экземпляр PropTypesPresenter'a, но не понял почему. Можешь объяснить или сказать что гуглить?

2021-06-10 13:32 UTC, Ensaphelon commented
> Я подумал, что импортируя TaskPresenter, каждый раз должен создаваться новый экземпляр PropTypesPresenter, так как в самом TaskPresenter'e написано "export default new PropTypesPresenter". Но я вписал в конструктор PropTypesPresenter'a вывод в консоль, и он сработал только один раз. т.е. я так понял что всё таки создаётся только один экземпляр PropTypesPresenter'a, но не понял почему. Можешь объяснить или сказать что гуглить?

`export default new PropTypesPresenter`

этот код экспортирует экземпляр, который создастся один раз на момент компиляции кода. Я так это понимаю. Если ты хочешь чтобы код конструктора вызывался столько раз сколько ты импортируешь класс - то импортировать нужно не инстанс класса а сам класс, и в том месте где ты его вызываешь нужно будет использовать оператор `new`.

2021-06-10 13:35 UTC, the38th commented
понял, спасибо

2021-06-10 13:36 UTC, Ensaphelon requested changes

2021-06-10 13:36 UTC, Ensaphelon commented on app/javascript/components/AddPopup/AddPopup.js
> +          <Form errors={errors} onChange={changeTask} task={task} handleChangeSelect={handleChangeSelect} />
onSelectChange={handleSelectChange}

2021-06-10 13:36 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +  const [isFocused, setFocus] = useState(false);
скорее всего нам этот стейт не нужен

2021-06-10 13:36 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            getOptionValue={(user) => UserPresenter.id(user)}
getOptionValue={UserPresenter.id}

выше то же самое

2021-06-10 13:36 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            onBlur={() => setFocus(false)}
onFocus, onBlur давай убирать

2021-06-27 17:05 UTC, Ensaphelon approved these changes

2021-06-28 05:34 UTC, closed without merging