Feature/redux
the38th/TaskManager pull request #23
Opened 2021-06-08 14:39 UTC by the38th

2021-06-09 13:10 UTC, Ensaphelon requested changes

2021-06-09 13:10 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +  const handleCloseEditPopup = () => {
handle{Object}{Action} - handleEditPopupClose

проверь это везде

2021-06-09 13:10 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +  const handleClose = () => {
close what?

2021-06-09 13:14 UTC, the38th commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +  const handleClose = () => {
а вы просто с конца начали или предыдущие 2 PR'а не видно?

2021-06-10 13:20 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +  const handleClose = () => {
с конца начали, видимо. Вижу другие PR-ы

2021-06-10 13:38 UTC, Ensaphelon approved these changes

2021-06-28 05:34 UTC, closed without merging